import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Post: NextPage = (props:any) => {
  console.log("props ==>",props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>SINGLE POST</h1>

    </div>
  )
}
export async function getStaticPaths() {
    // When this is true (in preview environments) don't
    // prerender any static pages
    // (faster builds, but slower initial page load)
    if (process.env.SKIP_BUILD_STATIC_GENERATION) {
      return {
        paths: [],
        fallback: 'blocking',
      }
    }
  
    // Call an external API endpoint to get posts
    const res = await fetch('https://dummyjson.com/products')
    const Products = await res.json()
  
    // Get the paths we want to prerender based on Product
    // In production environments, prerender all pages
    // (slower builds, but faster initial page load)
    const paths = Products.map((peoduct:any) => ({
      params: { id: peoduct.id },
    }))
  
    // { fallback: false } means other routes should 404
    return { paths, fallback: false }
}

export default Post
